-- AlterTable
ALTER TABLE "GroupMembership"
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "GroupMembership" ALTER COLUMN "updatedAt" DROP DEFAULT;
