export const AUDIT_ACTIONS = {
  GROUP_DELETED: "GROUP_DELETED",
  EVENT_DELETED: "EVENT_DELETED",
  GROUP_MEMBER_REMOVED: "GROUP_MEMBER_REMOVED",
  GROUP_MEMBER_ROLE_CHANGED: "GROUP_MEMBER_ROLE_CHANGED",
  TASK_APPROVED: "TASK_APPROVED",
  TASK_REJECTED: "TASK_REJECTED",
  IMPERSONATION_START: "IMPERSONATION_START",
  IMPERSONATION_END: "IMPERSONATION_END",
  SECURITY_LOGOUT_ALL_DEVICES: "SECURITY_LOGOUT_ALL_DEVICES"
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_TARGET_TYPES = {
  GROUP: "GROUP",
  EVENT: "EVENT",
  GROUP_MEMBERSHIP: "GROUP_MEMBERSHIP",
  TASK: "TASK",
  IMPERSONATION: "IMPERSONATION",
  USER: "USER"
} as const;

export type AuditTargetType = (typeof AUDIT_TARGET_TYPES)[keyof typeof AUDIT_TARGET_TYPES];
